vaultguard/home/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.register_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('home:login')), name='logout'),
    path('home/', views.home, name='home'),
    path('add-password/', views.add_password, name='add_password'),
    path('manage-password/', views.manage_password, name='manage_password'),
    path('edit-password/<id>', views.edit_password, name='edit_password'),
    path('delete-password/<id>', views.delete_password, name='delete_password'),
]

vaultguard/vaultguard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
]

vaultguard/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserPassword(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=500)
    application_type = models.CharField(max_length=100)
    website_name = models.CharField(max_length=50, blank=True)
    website_url = models.CharField(max_length=100, blank=True)
    application_name = models.CharField(max_length=50, blank=True)
    game_name = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self) -> str:
        app_name = ""
        if self.website_name:
            app_name = self.website_name
        elif self.application_name:
            app_name = self.application_name
        elif self.game_name:
            app_name = self.game_name
        return f'{app_name} password' 

vaultguard/home/forms.py
from typing import Any, Dict
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import UserPassword


class RegitrationForm(UserCreationForm):
    # Form to create new user
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'}
        ),
    )
    password2 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}
        ),
    )

    class Meta:
        model = User
        fields = ('username', 'email',)

        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Username'}
            ),
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'placeholder': 'Email'}
            )
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Username'}
        ),
    )
    password = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'}
        ),
    )


class UpdatePasswordsForm(forms.ModelForm):
    class Meta:
        model = UserPassword
        fields = ['id', 'username', 'password', 'application_type',
                  'website_name', 'website_url', 'application_name', 'game_name']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username'
            }),
            'password': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Password'
            }),
            'application_type': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Application Type', 'readonly': 'readonly'
            }),
            'website_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Website Name'
            }),
            'website_url': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Website url'
            }),
            'application_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Application Name'
            }),
            'game_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Game Name'
            }),
        }

    def clean(self):
        cleaned_data = super().clean()
        application_type = cleaned_data.get('application_type')
        application_name = cleaned_data.get('application_name')
        website_name = cleaned_data.get('website_name')
        website_url = cleaned_data.get('website_url')
        game_name = cleaned_data.get('game_name')

        if application_type == 'Website' and not website_name:
            raise ValidationError({'website_name': 'Website name is required.'})

        if application_type == 'Website' and not website_url:
            raise ValidationError({'website_url': 'Website url is required.'})

        if application_type == 'Desktop Application' and not application_name:
            raise ValidationError({'application_name': 'Application name is required.'})

        if application_type == 'Game' and not game_name:
            raise ValidationError({'game_name': 'Game name is required.'})

vaultguard/home/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import RegitrationForm, LoginForm, UpdatePasswordsForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.db.models import Q
from .models import UserPassword
from .utils import encrypt, decrypt


# Create your views here.


def index(request):
    return render(request, 'home/index.html')


def register_user(request):
    if request.method == "POST":
        form = RegitrationForm(request.POST or None)

        if form.is_valid():
            form.save()
            messages.success(
                request, 'Account created successfully. Please login to your account')

    else:
        form = RegitrationForm()
    return render(request, 'home/signup.html', {'form': form})


class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'home/login.html'

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        messages.success(self.request, f'Welcome {form.get_user()}')
        return super().form_valid(form)


def login_user(request):
    if request.user.is_authenticated:
        redirect('home:index')
    return UserLoginView.as_view()(request)


@login_required(login_url='home:login')
def home(request):
    return render(request, 'home/home.html')


@login_required(login_url='home:login')
def add_password(request):
    if request.method == "POST":
        username = request.POST['username']
        password = encrypt(request.POST['password'])
        application_type = request.POST['application_type']

        if application_type == "Website":
            website_name = request.POST['website_name']
            website_url = request.POST['website_url']
            UserPassword.objects.create(user=request.user, username=username, password=password,
                                        application_type=application_type, website_name=website_name, website_url=website_url)
            messages.success(request, 'New password added...!')

        elif application_type == "Desktop Application":
            application_name = request.POST['application_name']
            UserPassword.objects.create(user=request.user, username=username, password=password,
                                        application_type=application_type, application_name=application_name)
            messages.success(request, 'New password added...!')

        elif application_type == "Game":
            game_name = request.POST['game_name']
            UserPassword.objects.create(user=request.user, username=username,
                                        password=password, application_type=application_type, game_name=game_name)
            messages.success(request, 'New password added...!')
        return render(request, 'home/add-password.html')

    return render(request, 'home/add-password.html')


@login_required(login_url='home:login')
def manage_password(request):
    user = request.user
    password_list = UserPassword.objects.filter(
        user=user).order_by('-created_at')

    if request.method == "POST":
        print(request.POST)
        if 'clear_filter' in request.POST:
            password_list = UserPassword.objects.filter(
                user=user).order_by('-created_at')
            return render(request, 'home/manage-password.html', {'password_list': password_list})

        search_key = request.POST.get('search')

        if password_list.filter(Q(username__icontains=search_key) | Q(application_type__icontains=search_key) | Q(website_name__icontains=search_key) | Q(application_name__icontains=search_key) | Q(game_name__icontains=search_key)):

            password_list = password_list.filter(Q(username__icontains=search_key) | Q(application_type__icontains=search_key) | Q(website_name__icontains=search_key) | Q(application_name__icontains=search_key) | Q(game_name__icontains=search_key))
        else:
            messages.error(request, "Search Password does not Exist...!")

    context = {
        'password_list': password_list,
    }
    return render(request, 'home/manage-password.html', context)


@login_required(login_url='home:login')
def edit_password(request, id):
    user_password = UserPassword.objects.get(id=id)
    user_password.password = decrypt(user_password.password)
    form = UpdatePasswordsForm(instance=user_password)

    if request.method == "POST":
        form = UpdatePasswordsForm(request.POST, instance=user_password)
        if form.is_valid():
            try:
                user_password.password = encrypt(user_password.password)
                form.save()
                messages.success(request, 'Password updated.')
                user_password.password = decrypt(user_password.password)
            except ValidationError as e:
                form.add_error(e)

    context = {
        'form': form,
    }
    return render(request, 'home/edit-password.html', context)


@login_required(login_url='home:login')
def delete_password(request, id):
    password_obj = UserPassword.objects.get(id=id)
    password_obj.delete()
    return redirect('home:manage_password')

vaultguard/home/templates/home/add-password.html
{% extends "base.html" %}
{% load static %}

{% block body %}

<div class="row justify-content-center align-items-center">
    <div class="col-lg-6 col-12 p-4">
        <div class="card">
            <img src="{% static 'assets/images/Completed-rafiki.svg' %}" class="card-img-top" alt=""
                style="height: 15rem; object-fit: cover;">
            <div class="card-body py-5 px-5">
                <h2 class="card-title fw-bold text-primary-emphasis">Add new password</h2>
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" name="username" id="floatingInput" placeholder="">
                        <label for="floatingInput" class="text-muted">Username</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" name="password" id="floatingInput" placeholder="">
                        <label for="floatingInput" class="text-muted">Password</label>
                    </div>
                    <div class="mb-3">
                        <select class="form-select py-3" name="application_type" id="floatingInput"
                            placeholder="Appliction type" onchange="addFields(this)">
                            <option value="" selected>Application type</option>
                            <option value="Website">Website</option>
                            <option value="Desktop Application">Desktop Application</option>
                            <option value="Game">Game</option>
                        </select>
                    </div>
                    <div id="dynamic_input_field_container"></div>

                    <button type="submit" class="btn btn-success py-2 px-3">Add</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

vaultguard/home/templates/home/edit-password.html
{% extends "base.html" %}
{% load static %}

{% block body %}

<div class="row justify-content-center align-items-center">
    <div class="col-lg-6 col-12 p-4">
        <div class="card">
            <img src="{% static 'assets/images/Completed-rafiki.svg' %}" class="card-img-top" alt=""
                style="height: 15rem; object-fit: cover;">
            <div class="card-body py-5 px-5">
                <h2 class="card-title fw-bold text-primary-emphasis">Edit password</h2>
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
                <form action="" method="post">
                    {% csrf_token %}
                    {% if form.errors %}
                    <div class="text-danger">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <p>{{field.label}}: {{error}}</p>
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="form-floating mb-3">
                        {{form.username}}
                        <label for="floatingInput" class="text-muted">Username</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{ form.password }}
                        <label for="floatingInput" class="text-muted">Password</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.application_type}}
                        <label for="floatingInput" class="text-muted">Application Type</label>
                    </div>

                    {% if form.application_type.value == "Website" %}
                    <div class="form-floating mb-3">
                        {{form.website_name}}
                        <label for="floatingInput" class="text-muted">Website Name</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.website_url}}
                        <label for="floatingInput" class="text-muted">Website Url</label>
                    </div>
                    {% elif form.application_type.value == "Desktop Application" %}
                    <div class="form-floating mb-3">
                        {{form.application_name}}
                        <label for="floatingInput" class="text-muted">Application Name</label>
                    </div>
                    {% elif form.application_type.value == "Game" %}
                    <div class="form-floating mb-3">
                        {{form.game_name}}
                        <label for="floatingInput" class="text-muted">Game Name</label>
                    </div>
                    {% endif %}
                    

                    <button type="submit" class="btn btn-success py-2 px-3">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

vaultguard/home/templates/home/home.html
{% extends "base.html" %}
{% load static %}

{% block body %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<div class="row justify-content-center align-items-center">
    <div class="col-lg-6 col-12 p-4">
        <h1 class="main-headline fw-bolder text-primary-emphasis">Welcome to VaultGuard our password manager app
        </h1>
        <h5 class="fw-semibold sub-heading">Manage your all password from one place. Secure, fast and usefull.
        </h5>
        <div class="d-flex mt-3">
            <a href="{% url 'home:add_password' %}" class="btn btn-primary py-2 px-4 me-4"><span>Add Password</span> <i class="fa fa-plus"></i></a>
            <a href="{% url 'home:manage_password' %}" class="btn btn-primary py-2 px-4"><span>View All</span> <i class="fas fa-eye"></i></a>
        </div>
    </div>
    <div class="col-lg-6 col-12">
        <img src="{% static 'assets/images/20547283_6310505.svg' %}" alt="">
    </div>
</div>
{% endblock %}

vaultguard/home/templates/home/index.html
{% extends "base.html" %}
{% load static %}

{% block body %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<div class="row justify-content-center align-items-center">
    <div class="col-lg-6 col-12 p-4">
        <h1 class="main-headline fw-bolder text-primary-emphasis">VaultGuard our password manager app</h1>
        <h5 class="fw-semibold sub-heading">Manage your all password from one place. Secure, fast and usefull.
        </h5>
        <div class="d-flex mt-3">
            <a href="{% url 'home:login' %}" class="btn btn-primary py-2 px-3">Start Now</a>
        </div>
    </div>
    <div class="col-lg-6 col-12">
        <img src="{% static 'assets/images/Vault-rafiki.svg' %}" alt="">
    </div>
</div>
{% endblock %}

vaultguard/home/templates/home/login.html
{% extends "base.html" %}
{% load static %}

{% block body %}
<div class="row justify-content-center align-items-center">
    <div class="col-lg-6 col-12">
        <img src="{% static 'assets/images/20547283_6310505.svg' %}" alt="">
    </div>
    <div class="col-lg-6 col-12 p-4 row justify-content-center">
        <div class="col-lg-10">


            <h2 class="fw-semibold text-primary-emphasis">Welcome to VaultGuard. To use this app please login or signup.
            </h2>
            <div class="mt-4">
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
                <form action="" method="post" class="">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                        <div class="text-danger mb-3">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                    <div class="form-floating mb-3">
                        {{form.username}}
                        <label for="floatingInput" class="text-muted">Username</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.password}}
                        <label for="floatingPassword" class="text-muted">Password</label>
                    </div>
                    <div class="mb-3">
                        <input type="submit" value="Login" class="btn btn-success col-12 py-2">
                    </div>
                    <div class="divider d-flex align-items-center my-3">
                        <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
                    </div>
                </form>
                <a href="{% url 'home:signup' %}" class="btn btn-primary col-12 py-2">Signup</a>
            </div>
        </div>
    </div>

</div>
{% endblock %}

vaultguard/home/templates/home/manage-password.html
{% extends "base.html" %}
{% load static %}
{% load decrypt_tags %}

{% block body %}

<div class="row justify-content-center align-items-center">
    <div class="col-12 overflow-x-auto p-4">
        <h2 class="fw-bold text-primary-emphasis">Manage Password</h2>
        <div class="my-4">
            <form action="" method="post" class="row">
                {% csrf_token %}
                <div class="col-10">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search" id="search" placeholder="Search">
                        <button type="submit" class="btn btn-outline-primary">Search</button>
                    </div>
                </div>
                <div class="col-2">
                    <button class="btn btn-danger" name="clear_filter" type="submit">Clear Filter</button>
                </div>
            </form>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div {% if message.tags == 'error' %} class="alert alert-danger alert-dismissible fade show" 
        {% else %}
            class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        <div>
            {% if not password_list %}
            <h5 class="text-danger">No Password added...!</h5>
            {% else %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Username</th>
                        <th scope="col">Password</th>
                        <th scope="col">Application Type</th>
                        <th scope="col">Application Name</th>
                        <th scope="col">Detail(Url)</th>
                        <th scope="col">Created At</th>
                        <th scope="col">Last Update</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="text-muted">
                    {% for password in password_list %}
                    <tr>
                        <td scope="row">{{forloop.counter}}</td>
                        <td>{{password.username}}</td>
                        <td>
                            <div class="input-group input-group-sm">
                                <input class="form-control" type="password" id="{{forloop.counter}}"
                                    value="{{ password.password | decrypt_password }}" disabled readonly>
                                <div class="input-group-append">
                                    <button onclick="toggleView('{{forloop.counter}}')"
                                        class="btn btn-sm btn-outline-secondary" type="button" id="view-password">
                                        <i id="icon-{{forloop.counter}}" class="fas fa-eye-slash"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        <td>{{password.application_type}}</td>

                        {% if password.website_name %}
                        <td>{{password.website_name}}</td>
                        {% elif password.application_name %}
                        <td>{{password.application_name}}</td>
                        {% elif password.game_name %}
                        <td>{{password.game_name}}</td>
                        {% endif %}

                        {% if password.website_url %}
                        <td>{{password.website_url}}</td>
                        {% else %}
                        <td></td>
                        {% endif %}

                        <td>{{password.created_at}}</td>
                        <td>{{password.updated_at}}</td>
                        <td>
                            <a class="me-1" href="{% url 'home:edit_password' password.id %}">Edit</a>
                            <a href="" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</a>
                        </td>
                    </tr>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure to delete this
                                        password?</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close</button>
                                    <a href="{% url 'home:delete_password' password.id %}" type="button"
                                        class="btn btn-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

vaultguard/home/templates/home/signup.html
{% extends "base.html" %}
{% load static %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-lg-6 col-12">
        <img src="{% static 'assets/images/Mobile login-pana.svg' %}" alt="">
    </div>
    <div class="col-lg-6 col-12 p-4 row justify-content-center">
        <div class="col-lg-10">


            <h2 class="fw-semibold text-primary-emphasis">New to VaultGuard app? Please signup and maintain your
                password easily</h2>
            <div class="mt-4">
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
                <form action="" method="post" class="">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        {{form.username}}
                        <label for="floatingInput" class="text-muted">Username</label>
                        <span class="text-danger">{{form.username.errors}}</span>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.email}}
                        <label for="floatingInput" class="text-muted">Email address</label>
                        <span class="text-danger">{{form.email.errors}}</span>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.password1}}
                        <label for="floatingPassword" class="text-muted">Password</label>
                        <span class="text-danger">{{form.password1.errors}}</span>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.password2}}
                        <label for="floatingPassword" class="text-muted">Confirm Passowrd</label>
                        <span class="text-danger">{{form.password2.errors}}</span>
                    </div>
                    <div class="mb-3">
                        <input type="submit" value="Signup" class="btn btn-success col-12 py-2">
                    </div>
                    <div class="divider d-flex align-items-center my-3">
                        <p class="text-center fw-bold mx-3 mb-0 text-muted">Already have an account?</p>
                    </div>
                </form>
                <a href="{% url 'home:login' %}" class="btn btn-primary col-12 py-2">Login</a>
            </div>
        </div>
    </div>

</div>
{% endblock %}