vaultguard/home/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.register_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('home:login')), name='logout'),
    path('home/', views.home, name='home'),
    path('add-password/', views.add_password, name='add_password'),
    path('manage-password/', views.manage_password, name='manage_password'),
    path('edit-password/<id>', views.edit_password, name='edit_password'),
    path('delete-password/<id>', views.delete_password, name='delete_password'),
]

vaultguard/vaultguard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
]

vaultguard/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserPassword(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=500)
    application_type = models.CharField(max_length=100)
    website_name = models.CharField(max_length=50, blank=True)
    website_url = models.CharField(max_length=100, blank=True)
    application_name = models.CharField(max_length=50, blank=True)
    game_name = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self) -> str:
        app_name = ""
        if self.website_name:
            app_name = self.website_name
        elif self.application_name:
            app_name = self.application_name
        elif self.game_name:
            app_name = self.game_name
        return f'{app_name} password' 

vaultguard/home/forms.py
from typing import Any, Dict
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import UserPassword


class RegitrationForm(UserCreationForm):
    # Form to create new user
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'}
        ),
    )
    password2 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}
        ),
    )

    class Meta:
        model = User
        fields = ('username', 'email',)

        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Username'}
            ),
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'placeholder': 'Email'}
            )
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Username'}
        ),
    )
    password = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'}
        ),
    )


class UpdatePasswordsForm(forms.ModelForm):
    class Meta:
        model = UserPassword
        fields = ['id', 'username', 'password', 'application_type',
                  'website_name', 'website_url', 'application_name', 'game_name']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username'
            }),
            'password': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Password'
            }),
            'application_type': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Application Type', 'readonly': 'readonly'
            }),
            'website_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Website Name'
            }),
            'website_url': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Website url'
            }),
            'application_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Application Name'
            }),
            'game_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Game Name'
            }),
        }

    def clean(self):
        cleaned_data = super().clean()
        application_type = cleaned_data.get('application_type')
        application_name = cleaned_data.get('application_name')
        website_name = cleaned_data.get('website_name')
        website_url = cleaned_data.get('website_url')
        game_name = cleaned_data.get('game_name')

        if application_type == 'Website' and not website_name:
            raise ValidationError({'website_name': 'Website name is required.'})

        if application_type == 'Website' and not website_url:
            raise ValidationError({'website_url': 'Website url is required.'})

        if application_type == 'Desktop Application' and not application_name:
            raise ValidationError({'application_name': 'Application name is required.'})

        if application_type == 'Game' and not game_name:
            raise ValidationError({'game_name': 'Game name is required.'})

vaultguard/home/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import RegitrationForm, LoginForm, UpdatePasswordsForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.db.models import Q
from .models import UserPassword
from .utils import encrypt, decrypt


# Create your views here.


def index(request):
    return render(request, 'home/index.html')


def register_user(request):
    if request.method == "POST":
        form = RegitrationForm(request.POST or None)

        if form.is_valid():
            form.save()
            messages.success(
                request, 'Account created successfully. Please login to your account')

    else:
        form = RegitrationForm()
    return render(request, 'home/signup.html', {'form': form})


class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'home/login.html'

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        messages.success(self.request, f'Welcome {form.get_user()}')
        return super().form_valid(form)


def login_user(request):
    if request.user.is_authenticated:
        redirect('home:index')
    return UserLoginView.as_view()(request)


@login_required(login_url='home:login')
def home(request):
    return render(request, 'home/home.html')


@login_required(login_url='home:login')
def add_password(request):
    if request.method == "POST":
        username = request.POST['username']
        password = encrypt(request.POST['password'])
        application_type = request.POST['application_type']

        if application_type == "Website":
            website_name = request.POST['website_name']
            website_url = request.POST['website_url']
            UserPassword.objects.create(user=request.user, username=username, password=password,
                                        application_type=application_type, website_name=website_name, website_url=website_url)
            messages.success(request, 'New password added...!')

        elif application_type == "Desktop Application":
            application_name = request.POST['application_name']
            UserPassword.objects.create(user=request.user, username=username, password=password,
                                        application_type=application_type, application_name=application_name)
            messages.success(request, 'New password added...!')

        elif application_type == "Game":
            game_name = request.POST['game_name']
            UserPassword.objects.create(user=request.user, username=username,
                                        password=password, application_type=application_type, game_name=game_name)
            messages.success(request, 'New password added...!')
        return render(request, 'home/add-password.html')

    return render(request, 'home/add-password.html')


@login_required(login_url='home:login')
def manage_password(request):
    user = request.user
    password_list = UserPassword.objects.filter(
        user=user).order_by('-created_at')

    if request.method == "POST":
        print(request.POST)
        if 'clear_filter' in request.POST:
            password_list = UserPassword.objects.filter(
                user=user).order_by('-created_at')
            return render(request, 'home/manage-password.html', {'password_list': password_list})

        search_key = request.POST.get('search')

        if password_list.filter(Q(username__icontains=search_key) | Q(application_type__icontains=search_key) | Q(website_name__icontains=search_key) | Q(application_name__icontains=search_key) | Q(game_name__icontains=search_key)):

            password_list = password_list.filter(Q(username__icontains=search_key) | Q(application_type__icontains=search_key) | Q(website_name__icontains=search_key) | Q(application_name__icontains=search_key) | Q(game_name__icontains=search_key))
        else:
            messages.error(request, "Search Password does not Exist...!")

    context = {
        'password_list': password_list,
    }
    return render(request, 'home/manage-password.html', context)


@login_required(login_url='home:login')
def edit_password(request, id):
    user_password = UserPassword.objects.get(id=id)
    user_password.password = decrypt(user_password.password)
    form = UpdatePasswordsForm(instance=user_password)

    if request.method == "POST":
        form = UpdatePasswordsForm(request.POST, instance=user_password)
        if form.is_valid():
            try:
                user_password.password = encrypt(user_password.password)
                form.save()
                messages.success(request, 'Password updated.')
                user_password.password = decrypt(user_password.password)
            except ValidationError as e:
                form.add_error(e)

    context = {
        'form': form,
    }
    return render(request, 'home/edit-password.html', context)


@login_required(login_url='home:login')
def delete_password(request, id):
    password_obj = UserPassword.objects.get(id=id)
    password_obj.delete()
    return redirect('home:manage_password')

vaultguard/home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VaultGuard {% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css"
        integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">

    <!-- Custom css link -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary p-3">
        <div class="container-fluid mx-5 my-1">
            <div class="logo me-3">
                <img src="{% static 'assets/images/logo.png' %}" alt="VaultGuard" class="rounded-circle">
            </div>
            <a class="navbar-brand fw-semibold text-muted" {% if user.is_authenticated %} href="{% url 'home:home' %}" {% else %} href="{% url 'home:index' %}" {% endif %}>VaultGuard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:add_password' %}">Add Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:manage_password' %}">Manage Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>


    <!-- Main Body -->
    <div class="container mt-1">
        {% block body %}
        {% endblock %}
    </div>


    <!-- Bootstrap JS link -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>

    <!-- Custom js link -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>